(async()=>{'use strict';const A=window.Akram,$=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let c,rows=[],current;const status=m=>$('#status').textContent=m;
try{if(!A.enabled)throw Error('Run setup and enable backend first / Marka hore rakib nidaamka.');c=await A.client();if(!await A.user()){status('Sign in with the owner account / Ku soo gal akoonka milkiilaha.');const a=document.createElement('a');a.href='account.html?view=signin';a.textContent='Sign in / Soo gal';$('#status').append(a);return}if(!await A.admin())throw Error('Owner access required. Run 03_OWNER.sql for your verified owner account.');$('#workspace').hidden=false;await refresh();status('Connected / Maamulka waa ku xiran yahay.')}catch(e){status('Maamulka ma furmin / Setup required: '+e.message);return}
async function refresh(){rows=await A.rows();draw()}
function draw(){const query=$('#filter').value.toLowerCase();$('#book-list').innerHTML=rows.filter(r=>(r.data.title+' '+r.data.author).toLowerCase().includes(query)).map(r=>`<article class="admin-row"><img src="${esc(A.safeURL(r.data.cover)||'')}" alt=""><div class="meta"><h3>${esc(r.data.title)}</h3><p>${esc(r.data.author)} · ${esc(r.data.language)}</p><span class="badge">$${Number(r.price).toFixed(2)} · ${r.archived?'Archived / La saaray':r.published?'Published / Muuqda':'Hidden / Qarsoon'}</span></div><div class="row-actions"><button data-edit="${esc(r.id)}">Edit / Beddel</button><button class="secondary" data-toggle="${esc(r.id)}">${r.published?'Hide / Qari':'Show / Muuji'}</button><button class="danger" data-archive="${esc(r.id)}">${r.archived?'Restore / Soo celi':'Remove / Ka saar'}</button></div></article>`).join('')||'<p>No books / Buug lama helin.</p>'}
$('#filter').oninput=draw;$('#new').onclick=()=>edit();$('#close-editor').onclick=()=>$('#editor').close();
function edit(id){current=rows.find(r=>r.id===id);const f=$('#book-form');f.reset();const d=current?.data||{};for(const n of ['title','author','translator','language','category','description','license','pageCount'])if(d[n]!=null)f.elements[n].value=d[n];f.elements.id.value=current?.id||'';f.elements.price.value=current?.price||0;f.elements.published.checked=current?.published||false;f.elements.download.checked=d.download!==false;$('#form-status').textContent='';$('#editor').showModal()}
$('#book-list').onclick=async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.edit){edit(b.dataset.edit);return}const id=b.dataset.toggle||b.dataset.archive,r=rows.find(r=>r.id===id);if(!r)return;if(b.dataset.archive&&!confirm(r.archived?'Restore book? / Soo celi?':'Remove from public collection? Existing buyers retain access. / Ka saar muuqaalka? Iibsadayaashii hore way akhrisan karaan.'))return;b.disabled=true;try{const change=b.dataset.toggle?{published:!r.published,archived:false}:{archived:!r.archived,published:false};A.check(await c.from('akram_books').update({...change,updated_at:new Date().toISOString()}).eq('id',id));await refresh()}catch(err){status(err.message)}finally{b.disabled=false}};
async function upload(bucket,path,file){A.check(await c.storage.from(bucket).upload(path,file,{upsert:false,contentType:file.type}));return path}
$('#book-form').onsubmit=async e=>{e.preventDefault();const f=e.target,b=$('#save');b.disabled=true;$('#form-status').textContent='Saving / Kaydinaya…';try{const id=current?.id||crypto.randomUUID(),price=Number(f.elements.price.value),pdf=f.elements.pdfFile.files[0],cover=f.elements.coverFile.files[0];if(pdf&&(pdf.type!=='application/pdf'||pdf.size>52428800))throw Error('PDF only; max 50 MB');if(cover&&(!['image/jpeg','image/png','image/webp'].includes(cover.type)||cover.size>5242880))throw Error('Cover must be JPG/PNG/WebP, max 5 MB');let path=current?.file_path||null;const d={...(current?.data||{}),id};for(const n of ['title','author','translator','language','category','description','license'])d[n]=f.elements[n].value.trim();d.pageCount=Number(f.elements.pageCount.value);d.download=price===0&&f.elements.download.checked;d.paid=price>0;d.price=price;d.listPrice=price;d.salesEnabled=true;d.languages=[d.language];if(cover){const ext=cover.type.split('/')[1];const cp=await upload('akram-covers',id+'/'+crypto.randomUUID()+'.'+ext,cover);d.cover=c.storage.from('akram-covers').getPublicUrl(cp).data.publicUrl}if(!d.cover)throw Error('Choose a cover / Dooro sawirka');if(pdf)path=await upload('akram-books',id+'/'+crypto.randomUUID()+'.pdf',pdf);if(price>0&&!path)throw Error('Paid books require a private PDF / Geli PDF gaar ah');if(!path&&!d.pdf&&!d.text)throw Error('Choose a PDF / Dooro PDF');if(path){d.pdf=null;d.text=null;d.source=null}if(price>0){d.pdf=null;d.text=null;d.source=null}A.check(await c.from('akram_books').upsert({id,data:d,price,published:f.elements.published.checked,archived:false,file_path:path,updated_at:new Date().toISOString()}));await refresh();$('#editor').close();status('Saved / Waa la kaydiyey.')}catch(err){$('#form-status').textContent=err.message}finally{b.disabled=false}};
async function orders(){try{const list=await A.orders();$('#order-list').innerHTML=list.map(o=>`<article class="order-card"><h3>${esc(rows.find(r=>r.id===o.book_id)?.data.title||o.book_id)}</h3><p><strong>$${Number(o.amount).toFixed(2)} · ${esc(o.method.toUpperCase())} · ${esc(o.status)}</strong></p><p>Transaction / Tixraac: <code>${esc(o.reference)}</code></p><p>Customer ID / Aqoonsiga: ${esc(o.user_id)}<br>Order: ${esc(o.id)}<br>${esc(new Date(o.created_at).toLocaleString())}</p>${o.status==='pending'?`<div class="row-actions"><button data-approve="${o.id}">Confirm received / Lacagtu way timid</button><button class="danger" data-reject="${o.id}">Reject / Diid</button></div>`:''}</article>`).join('')||'<p>No orders yet / Dalab ma jiro.</p>'}catch(e){status(e.message)}}
$('#order-list').onclick=async e=>{const b=e.target.closest('button');if(!b)return;const approve=!!b.dataset.approve;if(!confirm(approve?'Have you verified this exact payment in your provider account? / Lacagtan ma ku hubisay diiwaanka adeegga?':'Reject this request? / Diid codsigan?'))return;b.disabled=true;try{A.check(await c.rpc('akram_review_order',{p_order:b.dataset.approve||b.dataset.reject,p_approve:approve}));await orders();status(approve?'Access granted / Buugga waa loo furay.':'Rejected / Waa la diiday.')}catch(err){status(err.message);b.disabled=false}};
$('#refresh-orders').onclick=orders;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{$('#books').hidden=b.dataset.tab!=='books';$('#orders').hidden=b.dataset.tab!=='orders';if(b.dataset.tab==='orders')orders()});
$('#backup').onclick=async()=>{try{const data={version:1,exportedAt:new Date().toISOString(),books:await A.rows(),orders:await A.orders(),entitlements:A.check(await c.from('akram_entitlements').select('*'))};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='akram-data-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Data exported. PDFs, covers and auth users need separate backups / PDF-yada, sawirrada iyo akoonnadu waxay u baahan yihiin backup gaar ah.')}catch(e){status(e.message)}};
})();
