const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const fs=require('fs'),assert=require('assert');
(async()=>{const http=require('http'),path=require('path');const server=http.createServer((req,res)=>{const file=path.join(process.cwd(),'akram-upload-ready',decodeURIComponent(new URL(req.url,'http://local').pathname).replace(/^\//,'')||'index.html');try{const ext=path.extname(file);res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.webp':'image/webp','.jpg':'image/jpeg','.png':'image/png','.txt':'text/plain'})[ext]||'application/octet-stream');res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end()}});await new Promise(r=>server.listen(8765,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.AKRAM_CHROMIUM||(fs.existsSync('/tmp/akram-browser/chromium')?'/tmp/akram-browser/chromium':undefined),headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'],env:{...process.env,LD_LIBRARY_PATH:'/tmp/akram-browser/al2023/lib:/tmp/akram-browser',FONTCONFIG_PATH:'/tmp/akram-browser/fonts'}});
const books=JSON.parse(fs.readFileSync('akram-upload-ready/catalog.json','utf8'));const errors=[];let passed=0;function ok(v,m){assert(v,m);passed++;}

for(const width of [1440,390]){const ctx=await browser.newContext({viewport:{width,height:1000},deviceScaleFactor:1});const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));
await page.route('**/backend.js*',r=>r.fulfill({contentType:'text/javascript',body:`window.Akram={enabled:true,catalog:async()=>${JSON.stringify(books)},client:async()=>({auth:{onAuthStateChange:(cb)=>{cb('INITIAL_SESSION',null);return {data:{subscription:{unsubscribe(){}}}}},getSession:async()=>({data:{session:null}}),signOut:async()=>({error:null})}}),access:async()=>false,user:async()=>null,check:r=>{if(r.error)throw r.error;return r.data}};`}));
await page.route('**/rest/v1/akram_reviews*',r=>r.fulfill({contentType:'application/json',body:'[]'}));await page.route('**/rest/v1/rpc/akram_subscribe',r=>r.fulfill({contentType:'application/json',body:'null'}));

await page.goto('http://127.0.0.1:8765/',{waitUntil:'networkidle'});await page.locator('.lib-feature').waitFor();await page.evaluate(()=>{document.documentElement.style.scrollSnapType='none';document.documentElement.style.scrollBehavior='auto'});
ok(await page.locator('#english-collection .sf-book-card').count()===10,'10 English');ok(await page.locator('#somali-collection .sf-book-card').count()===books.filter(b=>b.language==='Somali').length,'all Somali');ok(await page.locator('#most-read .restored-room-image img').count()===1,'Room 03 restored');await page.locator('#most-read').screenshot({path:`akram-storefront-src/verification/room03-${width}.png`});
const extra=books.filter(b=>b.language==='English').find(b=>!['1342','2680','11','84','2701','1661'].includes(b.id));await page.locator('#collection-search').fill(extra.title);ok(await page.locator('#catalogue .sf-book-card').count()>=1,'search catalog works');await page.locator('#catalogue .sf-catalog-meta button').click();
await page.locator('#english-collection .sf-book-card').filter({hasText:'Meditations'}).locator('.sf-cover-button').click();await page.locator('.hardcover-leaf article p').first().waitFor();ok(await page.locator('.sf-immersive').count()===1,'cover opens reader');ok(await page.locator('.hardcover-leaf').count()===(width>=900?2:1),'responsive spread');await page.locator('.sf-reader-paper').focus();await page.keyboard.press('ArrowRight');ok(await page.locator('input[aria-label="Page number"]').inputValue()===(width>=900?'3':'2'),'next spread correct');await page.keyboard.press('Home');ok(await page.locator('input[aria-label="Page number"]').inputValue()==='1','first page');await page.locator('input[aria-label="Page number"]').fill('20');await page.locator('input[aria-label="Page number"]').press('Tab');await page.mouse.move(700,30);await page.waitForTimeout(400);await page.screenshot({path:`akram-storefront-src/verification/reader-${width}.png`});await page.getByRole('button',{name:'Text settings',exact:true}).click();await page.locator('.sf-reader-panel textarea').fill('Reader note');await page.getByRole('button',{name:'Save note / highlight',exact:true}).click();ok((await page.locator('.sf-reader-panel').textContent()).includes('Reader note'),'notes');await page.locator('.sf-panel-close').click();await page.getByRole('button',{name:'Close reader',exact:true}).click();ok(await page.locator('.sf-immersive').count()===0,'exit');await ctx.close();}
ok(errors.length===0,errors.join('\n'));console.log('PASS '+passed+' hardcover / collection checks');await browser.close();server.close();})().catch(e=>{console.error(e);process.exit(1)});
