let pdfjs;
async function loadPDFEngine(){if(!pdfjs){pdfjs=await import('./assets--pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='./assets--pdf.worker.mjs';}}
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let progressSync;let book,doc,page=1,zoom=1,task,taskRight,serial=0;
const key=()=>`akram-pdf-${book.id}`,saved=()=>{try{return JSON.parse(localStorage.getItem(key())||'{}')}catch{return {}}},save=v=>{try{localStorage.setItem(key(),JSON.stringify({...saved(),...v}));const list=JSON.parse(localStorage.getItem('akram-reading')||'{}');list[book.id]={page:page-1,updated:Date.now()};localStorage.setItem('akram-reading',JSON.stringify(list));}catch{}};
const spreadMode=()=>innerWidth>=900, pageStep=()=>spreadMode()?2:1;
async function render(){if(!doc)return;const token=++serial;$('#status').textContent='Opening page… / Bogga ayaa furmaya…';for(const t of [task,taskRight]){if(t){t.cancel();try{await t.promise}catch{}}}try{const second=$('#pdf-page-right');if(second)second.hidden=!spreadMode()||page>=doc.numPages;for(const [offset,canvas] of [[0,$('#pdf-page')],[1,second]]){if(!canvas||offset&&(!spreadMode()||page>=doc.numPages))continue;const p=await doc.getPage(page+offset);if(token!==serial)return;const base=p.getViewport({scale:1}),view=p.getViewport({scale:Math.min(2,1200/base.width)});canvas.width=view.width;canvas.height=view.height;canvas.style.width='100%';canvas.style.maxWidth='100%';const t=p.render({canvasContext:canvas.getContext('2d'),viewport:view});if(offset)taskRight=t;else task=t;await t.promise;if(token!==serial)return;}$('#page').value=page;$('#prev').disabled=page===1;$('#next').disabled=page+(spreadMode()?1:0)>=doc.numPages;$('#progress').value=page/doc.numPages*100;$('#status').textContent=`${page} / ${doc.numPages} · ${Math.round(page/doc.numPages*100)}%`;save({page});progressSync?.save(page-1);document.dispatchEvent(new Event('akram-page-rendered'));$('#bookmark').setAttribute('aria-pressed',saved().bookmark===page);const range=$('#pdf-range');if(range){range.max=doc.numPages;range.value=page;$('#pdf-percent').textContent=Math.round(page/doc.numPages*100)+'%';$('#pdf-page-left-number').textContent=page;$('#pdf-page-right-number').textContent=page<doc.numPages?page+1:''}const shell=$('.pdf-open-book');if(shell)shell.style.zoom=zoom;}catch(e){if(e.name!=='RenderingCancelledException')$('#status').textContent='Unable to open page. Try again. / Mar kale isku day.'}}
async function start(){try{$('#book-intro').hidden=true;$('#reading-desk').hidden=false;document.body.classList.add('immersive-active');if(!doc){await loadPDFEngine();$('#status').textContent='Loading… / Sug…';doc=await pdfjs.getDocument({url:book.pdf,isEvalSupported:false}).promise;$('#total').textContent='/ '+doc.numPages;$('#page').max=doc.numPages;const outline=await doc.getOutline();for(const entry of outline||[]){try{const dest=typeof entry.dest==='string'?await doc.getDestination(entry.dest):entry.dest;if(!dest)continue;const n=typeof dest[0]==='number'?dest[0]+1:await doc.getPageIndex(dest[0])+1;$('#toc').add(new Option(entry.title,n))}catch{}}}if(!progressSync)progressSync=await window.AkramReading?.open(book.id,'pdf',Math.max(0,(saved().page||1)-1));page=Math.min((progressSync?.page??((saved().page||1)-1))+1,doc.numPages);await render()}catch{$('#status').textContent='Book files could not load. Check the uploaded files and try again. / Faylasha buugga ma furmin; hubi faylasha oo mar kale isku day.';$('#retry').hidden=false;}}
try{const all=await window.Akram.catalog();const id=new URL(location.href).searchParams.get('book');book=all.find(b=>b.id===id);if(!book&&window.Akram.enabled)book=await window.Akram.one(id);if(book?.fileUnavailable){book.pdf=await window.Akram.file(book);}if(book?.paid){if(!await window.Akram.access(book.id)){location.replace('./index.html?offer='+encodeURIComponent(book.id)+'#bookshop');throw Error();}book.pdf=await window.Akram.file(book);}if(!book?.pdf)throw Error();document.title=book.title+' · Akram Library';$('#title').textContent=book.title;$('#credits').textContent=book.author+(book.translator?' · Turjume / Translator: '+book.translator:'');$('#rights').textContent=book.license;$('#download').href=book.pdf;$('#download').hidden=book.paid||!book.download;$('#book-intro').innerHTML=`<div class="book-sculpture"><img src="${esc(book.cover)}" alt="${esc(book.title)}"></div><div><span class="eyebrow">AKRAM · ${book.paid?'YOUR PURCHASED BOOK':'FREE READING COLLECTION'}</span><h1>${esc(book.title)}</h1><div class="credit-block"><p><b data-en="Written by" data-so="Qoraaga">Written by</b><br>${esc(book.author)}</p>${book.translator?`<p><b data-en="Translated by" data-so="Turjumaha">Translated by</b><br>${esc(book.translator)}</p>`:''}</div><p>${book.pageCount} · ${esc((book.languages||[book.language]).join(" / "))} <span>${book.paid?'pages · Purchased / La iibsaday':'pages · Free / Bilaash'}</span></p><div class="intro-actions"><button id="begin" data-en="Enter the reading room →" data-so="Bilow akhriska →">Enter the reading room →</button>${!book.paid&&book.download?`<a href="${esc(book.pdf)}" download>Download PDF / Soo dejiso ↓</a>`:''}</div><p class="rights">${esc(book.license)}</p></div>`;$('#begin').onclick=start;addBookExtras(all);window.applyLocale?.();if(new URL(location.href).searchParams.get('start')==='1')start()}catch{$('#book-intro').innerHTML='<div><h1>Book unavailable / Buugga lama helin</h1><a href="./index.html#books">← Back to library / Ku noqo maktabadda</a></div>'}
$('#prev').onclick=()=>{if(doc&&page>1){page=Math.max(1,page-pageStep());render()}};$('#next').onclick=()=>{if(doc&&page<doc.numPages){page=Math.min(doc.numPages,page+pageStep());render()}};$('#page').onchange=e=>{if(!doc)return;page=Math.max(1,Math.min(doc.numPages,parseInt(e.target.value)||1));render()};$('#toc').onchange=e=>{if(!doc)return;page=Number(e.target.value);render()};$('#zoom-minus').onclick=()=>{zoom=Math.max(.65,zoom-.15);render()};$('#zoom-plus').onclick=()=>{zoom=Math.min(2,zoom+.15);render()};$('#theme').onclick=()=>{const dark=document.body.classList.toggle('reader-dark');try{localStorage.setItem('akram-night',JSON.stringify(dark))}catch{}};$('#bookmark').onclick=()=>{save({bookmark:page});$('#bookmark').setAttribute('aria-pressed','true');$('#status').textContent='Bookmark saved / Calaamadda waa la kaydiyey'};$('#saved').onclick=()=>{page=saved().bookmark||1;render()};$('#fullscreen').onclick=()=>{(document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen()).catch(()=>{})};$('#show-intro').onclick=()=>{$('#book-intro').hidden=false;$('#reading-desk').hidden=true;document.body.classList.remove('immersive-active')};document.addEventListener('keydown',e=>{if($('#reading-desk').hidden||e.target.matches('input,select'))return;if(e.target.matches('textarea'))return;if(['ArrowRight','ArrowLeft',' ','Home','End'].includes(e.key))e.preventDefault();if(e.key==='ArrowRight'||e.key===' ')$('#next').click();if(e.key==='ArrowLeft')$('#prev').click();if(e.key==='Home'){page=1;render()}if(e.key==='End'&&doc){page=doc.numPages;render()}if(e.key.toLowerCase()==='f')$('#fullscreen').click();if(e.key.toLowerCase()==='b')$('#bookmark').click()});

$('#retry').onclick=()=>{$('#retry').hidden=true;start()};

try{document.body.classList.toggle('reader-dark',JSON.parse(localStorage.getItem('akram-night')||'false'))}catch{}
function addBookExtras(all){
 const node=document.createElement('div');node.className='book-extras';const related=all.filter(b=>b.id!==book.id&&!b.paid&&b.pdf&&(b.language===book.language||b.category===book.category)).slice(0,3);
 node.innerHTML=`<div class="book-info-grid"><div><small data-en="CATEGORY" data-so="QAYBTA">CATEGORY</small>${esc(book.category)}</div><div><small data-en="LANGUAGE" data-so="LUUQADDA">LANGUAGE</small>${esc((book.languages||[book.language]).join(' / '))}</div><div><small data-en="PAGES" data-so="BOGAGGA">PAGES</small>${book.pageCount}</div><div><small data-en="PUBLICATION" data-so="DAABACAADDA">PUBLICATION</small>${book.year?esc(book.year):'Not specified / Lama sheegin'}</div></div><div class="book-extra-actions"><button id="detail-favorite" aria-pressed="false">♡ Favorite / Jeclow</button><button id="detail-list">+ My Library / Maktabaddayda</button><button id="detail-share">↗ Share / La wadaag</button></div><p id="detail-feedback" role="status"></p><h2 data-en="You may also like" data-so="Kuwan sidoo kale waad jeclaan kartaa">You may also like</h2><div class="related-reader">${related.map(b=>`<a href="read.html?book=${encodeURIComponent(b.id)}"><img src="${esc(b.cover)}" alt="${esc(b.title)}"><span>${esc(b.title)}<br><small>${esc(b.author)}</small></span></a>`).join('')}</div>`;
 $('#book-intro').append(node);const read=(key,f)=>{try{return JSON.parse(localStorage.getItem(key))||f}catch{return f}};const refresh=()=>{const yes=read('akram-favorites',[]).includes(book.id);$('#detail-favorite').setAttribute('aria-pressed',String(yes));$('#detail-favorite').textContent=yes?'♥ Saved / Waa la kaydiyey':'♡ Favorite / Jeclow'};refresh();
 $('#detail-favorite').onclick=()=>{const f=read('akram-favorites',[]);try{localStorage.setItem('akram-favorites',JSON.stringify(f.includes(book.id)?f.filter(id=>id!==book.id):[...f,book.id]));refresh()}catch{$('#detail-feedback').textContent='Storage unavailable / Kaydintu ma shaqaynayso'}};
 $('#detail-list').onclick=()=>{try{const list=read('akram-reading',{});if(!list[book.id])list[book.id]={page:0,updated:Date.now()};localStorage.setItem('akram-reading',JSON.stringify(list));$('#detail-feedback').textContent='Added to My Library / Maktabaddayda waa lagu daray'}catch{$('#detail-feedback').textContent='Storage unavailable / Kaydintu ma shaqaynayso'}};
 $('#detail-share').onclick=async()=>{const url=new URL(location.href);url.searchParams.delete('start');try{if(navigator.share)await navigator.share({title:book.title,url:url.href});else{await navigator.clipboard.writeText(url.href);$('#detail-feedback').textContent='Link copied / Link-ga waa la koobiyeeyey'}}catch{$('#detail-feedback').textContent='Share this link / La wadaag link-gan: '+url.href}};
}

// Immersive controls; authentication and paid access remain in the existing loader.
const preferences=(()=>{try{return JSON.parse(localStorage.getItem('akram-pdf-preferences')||'{}')}catch{return {}}})();
let idleTimer,themeIndex=['day','sepia','night'].indexOf(preferences.theme||'day');
function setReadingTheme(){const theme=['day','sepia','night'][themeIndex];document.body.dataset.readingTheme=theme;document.body.classList.toggle('reader-dark',theme==='night');preferences.theme=theme;try{localStorage.setItem('akram-pdf-preferences',JSON.stringify(preferences))}catch{}}
setReadingTheme();$('#theme').onclick=()=>{themeIndex=(themeIndex+1)%3;setReadingTheme()};
function reveal(){document.body.classList.remove('controls-asleep');clearTimeout(idleTimer);idleTimer=setTimeout(()=>{if(!document.querySelector('.immersive-panel:not([hidden])'))document.body.classList.add('controls-asleep')},3000)}
document.addEventListener('pointermove',e=>{if(e.clientY<130||e.clientY>innerHeight-150)reveal()});document.addEventListener('keydown',reveal);document.addEventListener('touchstart',reveal,{passive:true});
const exit=document.createElement('a');exit.href='./index.html#books';exit.className='reader-exit';exit.textContent='← Library / Maktabadda';document.body.append(exit);
const extra=document.createElement('div');extra.className='immersive-panel';extra.hidden=true;extra.innerHTML='<button id="close-reading-tools">× Close / Xir</button><h2>Reading tools / Qalabka akhriska</h2><label>Search this book / Ka raadi buugga<input id="pdf-search" type="search"></label><button id="run-pdf-search">Search / Raadi</button><p id="pdf-search-status" role="status"></p><div id="pdf-search-results"></div><h3>Notes & page markers / Qoraallo</h3><textarea id="pdf-note" placeholder="Write a note for this page / Qor xusuus boggan"></textarea><button id="save-pdf-note">Save note / Kaydi</button><div id="pdf-notes"></div><p class="pdf-note-info">PDF pages retain the author’s layout. Use A− / A+ to zoom. Notes are saved on this device. / PDF-gu wuxuu hayaa qaabka qoraaga. Qoraalladu qalabkan ayay ku kaydsan yihiin.</p>';document.body.append(extra);
const toolsButton=document.createElement('button');toolsButton.textContent='☷ Tools / Qalabka';toolsButton.onclick=()=>{extra.hidden=!extra.hidden;reveal();showNotes()};$('.tools').append(toolsButton);$('#close-reading-tools').onclick=()=>{extra.hidden=true;reveal()};
function showNotes(){if(!book)return;const notes=saved().notes||[];const out=$('#pdf-notes');out.replaceChildren();notes.forEach((n,i)=>{const row=document.createElement('div'),jump=document.createElement('button'),text=document.createElement('p'),del=document.createElement('button');jump.textContent='Page / Bogga '+n.page;jump.onclick=()=>{page=n.page;render()};text.textContent=n.text;del.textContent='Delete / Tirtir';del.onclick=()=>{save({notes:notes.filter((_,j)=>j!==i)});showNotes()};row.append(jump,text,del);out.append(row)})}
$('#save-pdf-note').onclick=()=>{if(!book||!doc||!$('#pdf-note').value.trim())return;save({notes:[...(saved().notes||[]),{page,text:$('#pdf-note').value.trim()}]});$('#pdf-note').value='';showNotes()};
let searchSerial=0;$('#run-pdf-search').onclick=async()=>{if(!doc)return;const q=$('#pdf-search').value.trim().toLowerCase();if(q.length<2)return;const token=++searchSerial;const out=$('#pdf-search-results');out.replaceChildren();$('#pdf-search-status').textContent='Searching… / Raadin…';let found=0;for(let i=1;i<=doc.numPages;i++){if(token!==searchSerial)return;const p=await doc.getPage(i);const c=await p.getTextContent();if(c.items.map(v=>v.str||'').join(' ').toLowerCase().includes(q)){found++;const b=document.createElement('button');b.textContent='Page / Bogga '+i;b.onclick=()=>{page=i;render();extra.hidden=true};out.append(b)}if(i%5===0)await new Promise(r=>setTimeout(r,0))}$('#pdf-search-status').textContent=found?'Found / La helay: '+found:'No text match. Scanned pages may not contain searchable text. / Qoraal lama helin; bogag sawir ah raadintoodu ma shaqayso.'};
const stage=$('.page-stage');let touchX=0,lastWheel=0;stage.addEventListener('touchstart',e=>{touchX=e.touches[0].clientX},{passive:true});stage.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-touchX;if(Math.abs(dx)>90)$(dx<0?'#next':'#prev').click()},{passive:true});stage.addEventListener('click',e=>{const r=stage.getBoundingClientRect();if(e.clientX<r.left+r.width*.12)$('#prev').click();else if(e.clientX>r.right-r.width*.12)$('#next').click();else reveal()});stage.addEventListener('wheel',e=>{if(Date.now()-lastWheel<1000)return;const bottom=stage.scrollTop+stage.clientHeight>=stage.scrollHeight-3;if(e.deltaY>0&&bottom||e.deltaY<0&&stage.scrollTop===0){lastWheel=Date.now();$(e.deltaY>0?'#next':'#prev').click();stage.scrollTop=0}},{passive:true});reveal();

// Secondary controls live inside the drawer; the page stays visually quiet.
const advanced=document.createElement('div');advanced.className='pdf-appearance';advanced.innerHTML='<h3>Appearance / Muuqaalka</h3><p>Day · Sepia · Night</p>';extra.insertBefore(advanced,extra.children[1]);for(const id of ['zoom-minus','zoom-plus','theme','saved','download'])advanced.append(document.getElementById(id));
const toc=$('.toc-label');extra.insertBefore(toc,advanced.nextSibling);
const leaf=document.createElement('div');leaf.className='pdf-leaf';stage.insertBefore(leaf,$('#pdf-page'));leaf.append($('#pdf-page'));const layer=document.createElement('div');layer.className='pdf-highlights';leaf.append(layer);let marking=false,origin=null;
const highlightButton=document.createElement('button');highlightButton.id='highlight-mode';highlightButton.textContent='Highlight area / Calaamadee';highlightButton.onclick=()=>{marking=!marking;layer.classList.toggle('marking',marking);highlightButton.setAttribute('aria-pressed',String(marking));extra.hidden=true;reveal()};advanced.append(highlightButton);
function paintHighlights(){layer.replaceChildren();(saved().highlights||[]).filter(h=>h.page===page).forEach(h=>{const m=document.createElement('span');m.style.cssText='left:'+h.x*100+'%;top:'+h.y*100+'%;width:'+h.w*100+'%;height:'+h.h*100+'%';layer.append(m)})}document.addEventListener('akram-page-rendered',paintHighlights);
layer.addEventListener('pointerdown',e=>{if(!marking)return;e.preventDefault();e.stopPropagation();const r=layer.getBoundingClientRect();origin={x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height};layer.setPointerCapture(e.pointerId)});
layer.addEventListener('pointerup',e=>{if(!origin)return;e.preventDefault();e.stopPropagation();const r=layer.getBoundingClientRect();const x=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));const h={page,x:Math.min(x,origin.x),y:Math.min(y,origin.y),w:Math.abs(x-origin.x),h:Math.abs(y-origin.y)};if(h.w>.01&&h.h>.002)save({highlights:[...(saved().highlights||[]),h]});origin=null;marking=false;layer.classList.remove('marking');highlightButton.setAttribute('aria-pressed','false');paintHighlights()});
const clearHighlights=document.createElement('button');clearHighlights.textContent='Clear page highlights / Ka saar calaamadaha bogga';clearHighlights.onclick=()=>{save({highlights:(saved().highlights||[]).filter(h=>h.page!==page)});paintHighlights()};advanced.append(clearHighlights);

// Open hardcover spread with quiet chrome. Document content is never replaced.
const openBook=document.createElement('div');openBook.className='pdf-open-book';stage.insertBefore(openBook,leaf);openBook.append(leaf);leaf.classList.add('left-leaf');
const rightLeaf=document.createElement('div');rightLeaf.className='pdf-leaf right-leaf';const rightCanvas=document.createElement('canvas');rightCanvas.id='pdf-page-right';rightCanvas.setAttribute('aria-label','Next book page');rightLeaf.append(rightCanvas);openBook.append(rightLeaf);
for(const [node,id] of [[leaf,'pdf-page-left-number'],[rightLeaf,'pdf-page-right-number']]){const n=document.createElement('span');n.className='pdf-leaf-number';n.id=id;node.append(n)}
const chrome=document.createElement('div');chrome.className='hardcover-pdf-top';chrome.innerHTML='<div class="pdf-top-left"><a href="./index.html#books" aria-label="Close reader">×</a><button id="pdf-contents-open" aria-label="Table of contents">☷</button><button id="pdf-find-open" aria-label="Search">⌕</button></div><div class="pdf-top-title"><strong></strong><small></small></div><div class="pdf-top-right"></div>';
chrome.querySelector('strong').textContent=book?.title||'Akram Library';chrome.querySelector('small').textContent=book?.author||'';document.body.append(chrome);
for(const b of [$('#bookmark'),toolsButton,$('#theme')])chrome.querySelector('.pdf-top-right').append(b);toolsButton.textContent='Aa';toolsButton.setAttribute('aria-label','Reading tools');$('#theme').textContent='☼';$('#theme').setAttribute('aria-label','Reading theme');$('#pdf-contents-open').onclick=()=>{extra.hidden=false;reveal();$('#toc').focus()};$('#pdf-find-open').onclick=()=>{extra.hidden=false;reveal();$('#pdf-search').focus()};
const toolbar=$('.tools');const range=document.createElement('input');range.type='range';range.id='pdf-range';range.min=1;range.max=doc?.numPages||1;range.value=page;range.setAttribute('aria-label','Reading progress');range.oninput=e=>{if(!doc)return;page=Number(e.target.value);render()};toolbar.prepend(range);const middle=document.createElement('span');middle.className='pdf-progress-title';middle.textContent=book?.title||'';toolbar.append(middle);const percent=document.createElement('span');percent.id='pdf-percent';toolbar.append(percent);for(const id of ['prev','next']){const b=$('#'+id);b.classList.add('pdf-edge');document.body.append(b)}
exit.hidden=true;$('#status').classList.add('pdf-loading-status');let lastSpread=spreadMode();window.addEventListener('resize',()=>{if(lastSpread!==spreadMode()){lastSpread=spreadMode();render()}});if(doc)render();
for(const id of ['bookmark','theme']){const b=$('#'+id);b.removeAttribute('data-en');b.removeAttribute('data-so');b.textContent=id==='theme'?'☼':''}

window.addEventListener('pagehide',()=>progressSync?.close());
