let pdfjs;
async function loadPDFEngine(){if(!pdfjs){pdfjs=await import('./assets--pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='./assets--pdf.worker.mjs';}}
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let book,doc,page=1,zoom=1,task,serial=0;
const key=()=>`akram-pdf-${book.id}`,saved=()=>{try{return JSON.parse(localStorage.getItem(key())||'{}')}catch{return {}}},save=v=>{try{localStorage.setItem(key(),JSON.stringify({...saved(),...v}));const list=JSON.parse(localStorage.getItem('akram-reading')||'{}');list[book.id]={page:page-1,updated:Date.now()};localStorage.setItem('akram-reading',JSON.stringify(list));}catch{}};
async function render(){if(!doc)return;const token=++serial;$('#status').textContent='Opening page… / Bogga ayaa furmaya…';if(task){task.cancel();try{await task.promise}catch{}}try{const p=await doc.getPage(page);if(token!==serial)return;const view=p.getViewport({scale:Math.min(2,1400/p.getViewport({scale:1}).width)});const canvas=$('#pdf-page');canvas.width=view.width;canvas.height=view.height;canvas.style.width=`${820*zoom}px`;canvas.style.maxWidth=zoom>1?'none':'100%';task=p.render({canvasContext:canvas.getContext('2d'),viewport:view});await task.promise;if(token!==serial)return;$('#page').value=page;$('#prev').disabled=page===1;$('#next').disabled=page===doc.numPages;$('#progress').value=page/doc.numPages*100;$('#status').textContent=`${page} / ${doc.numPages} · ${Math.round(page/doc.numPages*100)}%`;save({page});$('#bookmark').setAttribute('aria-pressed',saved().bookmark===page)}catch(e){if(e.name!=='RenderingCancelledException')$('#status').textContent='Unable to open page. Try again. / Mar kale isku day.'}}
async function start(){try{$('#book-intro').hidden=true;$('#reading-desk').hidden=false;if(!doc){await loadPDFEngine();$('#status').textContent='Loading… / Sug…';doc=await pdfjs.getDocument({url:book.pdf,isEvalSupported:false}).promise;$('#total').textContent='/ '+doc.numPages;$('#page').max=doc.numPages;const outline=await doc.getOutline();for(const entry of outline||[]){try{const dest=typeof entry.dest==='string'?await doc.getDestination(entry.dest):entry.dest;if(!dest)continue;const n=typeof dest[0]==='number'?dest[0]+1:await doc.getPageIndex(dest[0])+1;$('#toc').add(new Option(entry.title,n))}catch{}}}page=Math.min(saved().page||1,doc.numPages);await render()}catch{$('#status').textContent='Book files could not load. Check the uploaded files and try again. / Faylasha buugga ma furmin; hubi faylasha oo mar kale isku day.';$('#retry').hidden=false;}}
try{const all=await window.Akram.catalog();const id=new URL(location.href).searchParams.get('book');book=all.find(b=>b.id===id);if(!book&&window.Akram.enabled)book=await window.Akram.one(id);if(book?.paid){if(!await window.Akram.access(book.id)){location.replace('./index.html?offer='+encodeURIComponent(book.id)+'#bookshop');throw Error();}book.pdf=await window.Akram.file(book);}if(!book?.pdf)throw Error();document.title=book.title+' · Akram Library';$('#title').textContent=book.title;$('#credits').textContent=book.author+(book.translator?' · Turjume / Translator: '+book.translator:'');$('#rights').textContent=book.license;$('#download').href=book.pdf;$('#download').hidden=book.paid||!book.download;$('#book-intro').innerHTML=`<div class="book-sculpture"><img src="${esc(book.cover)}" alt="${esc(book.title)}"></div><div><span class="eyebrow">AKRAM · ${book.paid?'YOUR PURCHASED BOOK':'FREE READING COLLECTION'}</span><h1>${esc(book.title)}</h1><div class="credit-block"><p><b data-en="Written by" data-so="Qoraaga">Written by</b><br>${esc(book.author)}</p>${book.translator?`<p><b data-en="Translated by" data-so="Turjumaha">Translated by</b><br>${esc(book.translator)}</p>`:''}</div><p>${book.pageCount} · ${esc((book.languages||[book.language]).join(" / "))} <span>${book.paid?'pages · Purchased / La iibsaday':'pages · Free / Bilaash'}</span></p><div class="intro-actions"><button id="begin" data-en="Enter the reading room →" data-so="Bilow akhriska →">Enter the reading room →</button>${!book.paid&&book.download?`<a href="${esc(book.pdf)}" download>Download PDF / Soo dejiso ↓</a>`:''}</div><p class="rights">${esc(book.license)}</p></div>`;$('#begin').onclick=start;addBookExtras(all);window.applyLocale?.();if(new URL(location.href).searchParams.get('start')==='1')start()}catch{$('#book-intro').innerHTML='<div><h1>Book unavailable / Buugga lama helin</h1><a href="./index.html#books">← Back to library / Ku noqo maktabadda</a></div>'}
$('#prev').onclick=()=>{if(doc&&page>1){page--;render()}};$('#next').onclick=()=>{if(doc&&page<doc.numPages){page++;render()}};$('#page').onchange=e=>{if(!doc)return;page=Math.max(1,Math.min(doc.numPages,parseInt(e.target.value)||1));render()};$('#toc').onchange=e=>{if(!doc)return;page=Number(e.target.value);render()};$('#zoom-minus').onclick=()=>{zoom=Math.max(.65,zoom-.15);render()};$('#zoom-plus').onclick=()=>{zoom=Math.min(2,zoom+.15);render()};$('#theme').onclick=()=>{const dark=document.body.classList.toggle('reader-dark');try{localStorage.setItem('akram-night',JSON.stringify(dark))}catch{}};$('#bookmark').onclick=()=>{save({bookmark:page});$('#bookmark').setAttribute('aria-pressed','true');$('#status').textContent='Bookmark saved / Calaamadda waa la kaydiyey'};$('#saved').onclick=()=>{page=saved().bookmark||1;render()};$('#fullscreen').onclick=()=>{(document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen()).catch(()=>{})};$('#show-intro').onclick=()=>{$('#book-intro').hidden=false;$('#reading-desk').hidden=true};document.addEventListener('keydown',e=>{if($('#reading-desk').hidden||e.target.matches('input,select'))return;if(e.key==='ArrowRight')$('#next').click();if(e.key==='ArrowLeft')$('#prev').click()});

$('#retry').onclick=()=>{$('#retry').hidden=true;start()};

try{document.body.classList.toggle('reader-dark',JSON.parse(localStorage.getItem('akram-night')||'false'))}catch{}
function addBookExtras(all){
 const node=document.createElement('div');node.className='book-extras';const related=all.filter(b=>b.id!==book.id&&!b.paid&&b.pdf&&(b.language===book.language||b.category===book.category)).slice(0,3);
 node.innerHTML=`<div class="book-info-grid"><div><small data-en="CATEGORY" data-so="QAYBTA">CATEGORY</small>${esc(book.category)}</div><div><small data-en="LANGUAGE" data-so="LUUQADDA">LANGUAGE</small>${esc((book.languages||[book.language]).join(' / '))}</div><div><small data-en="PAGES" data-so="BOGAGGA">PAGES</small>${book.pageCount}</div><div><small data-en="PUBLICATION" data-so="DAABACAADDA">PUBLICATION</small>${book.year?esc(book.year):'Not specified / Lama sheegin'}</div></div><div class="book-extra-actions"><button id="detail-favorite" aria-pressed="false">♡ Favorite / Jeclow</button><button id="detail-list">+ My Library / Maktabaddayda</button><button id="detail-share">↗ Share / La wadaag</button></div><p id="detail-feedback" role="status"></p><h2 data-en="You may also like" data-so="Kuwan sidoo kale waad jeclaan kartaa">You may also like</h2><div class="related-reader">${related.map(b=>`<a href="read.html?book=${encodeURIComponent(b.id)}"><img src="${esc(b.cover)}" alt="${esc(b.title)}"><span>${esc(b.title)}<br><small>${esc(b.author)}</small></span></a>`).join('')}</div>`;
 $('#book-intro').append(node);const read=(key,f)=>{try{return JSON.parse(localStorage.getItem(key))||f}catch{return f}};const refresh=()=>{const yes=read('akram-favorites',[]).includes(book.id);$('#detail-favorite').setAttribute('aria-pressed',String(yes));$('#detail-favorite').textContent=yes?'♥ Saved / Waa la kaydiyey':'♡ Favorite / Jeclow'};refresh();
 $('#detail-favorite').onclick=()=>{const f=read('akram-favorites',[]);try{localStorage.setItem('akram-favorites',JSON.stringify(f.includes(book.id)?f.filter(id=>id!==book.id):[...f,book.id]));refresh()}catch{$('#detail-feedback').textContent='Storage unavailable / Kaydintu ma shaqaynayso'}};
 $('#detail-list').onclick=()=>{try{const list=read('akram-reading',{});if(!list[book.id])list[book.id]={page:0,updated:Date.now()};localStorage.setItem('akram-reading',JSON.stringify(list));$('#detail-feedback').textContent='Added to My Library / Maktabaddayda waa lagu daray'}catch{$('#detail-feedback').textContent='Storage unavailable / Kaydintu ma shaqaynayso'}};
 $('#detail-share').onclick=async()=>{const url=new URL(location.href);url.searchParams.delete('start');try{if(navigator.share)await navigator.share({title:book.title,url:url.href});else{await navigator.clipboard.writeText(url.href);$('#detail-feedback').textContent='Link copied / Link-ga waa la koobiyeeyey'}}catch{$('#detail-feedback').textContent='Share this link / La wadaag link-gan: '+url.href}};
}
