(()=>{'use strict';
const dialog=document.getElementById('shop-offer');if(!dialog)return;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={phone:'M22 16.9v3a2 2 0 0 1-2.2 2A19.8 19.8 0 0 1 3.1 5.2 2 2 0 0 1 5.1 3h3a2 2 0 0 1 2 1.7l.5 2.8a2 2 0 0 1-.6 1.8L8.7 10.6a16 16 0 0 0 4.7 4.7l1.3-1.3a2 2 0 0 1 1.8-.6l2.8.5a2 2 0 0 1 1.7 2z',wallet:'M20 8V5H5a2 2 0 0 0 0 4h16v11H5a2 2 0 0 1-2-2V7m18 6h-5v3h5',shield:'M12 3 3 7v5c0 5 9 9 9 9s9-4 9-9V7z M8 12l3 3 5-6',sim:'M7 3h8l5 5v13H4V3z M8 11h8v7H8z M12 11v7 M8 14h8',arrow:'m9 5 7 7-7 7',info:'M12 11v6 M12 7v.1 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0'};
const icon=n=>`<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${paths[n].split(' M').map((d,i)=>`<path d="${i?'M':''}${d}"/>`).join('')}</svg>`;
const methods=[{id:'evc',name:'EVC',title:'EVC Plus',code:'*712*618248533*5#',tel:'*712*618248533*5%23'},{id:'edahab',name:'EDAHAB',title:'eDahab',code:'*112*628248533*5#',tel:'*112*628248533*5%23'},{id:'sim',name:'SIM',title:'SIM',code:'+252 618 248 533',tel:'+252618248533'}];
const brand=m=>m.id==='sim'?`<span class="pay-sim">SIM ${icon('sim')}</span>`:`<span role="img" aria-label="${m.title}" class="pay-brand pay-brand-${m.id}"></span>`;
let catalog;
window.showBookOffer=async id=>{try{
catalog=await window.Akram.catalog();
const b=catalog.find(x=>x.id===id&&x.paid);if(!b)throw Error('Book unavailable');
if(window.Akram.enabled&&await window.Akram.access(b.id)){location.href='read.html?book='+encodeURIComponent(b.id)+'&start=1';return;}
const ready=window.Akram.enabled&&!!b.privatePath;
const amount=Number(b.price).toFixed(2).replace(/\.00$/,'');
const payMethods=methods.map(m=>({...m,code:m.code.replace('*5#','*'+amount+'#'),tel:m.tel.replace('*5%23','*'+amount+'%23')}));
document.getElementById('offer-content').innerHTML=`<section class="pay-component"><div class="pay-book"><span>${esc(b.title)}</span><strong>$${Number(b.price).toFixed(2)}</strong></div><header class="pay-heading"><span class="pay-icon">${icon('wallet')}</span><div><h2 id="offer-title">PAYMENT METHOD / HABKA LACAG BIXINTA <em>*</em></h2><p>Choose how to pay / Dooro habka aad lacagta ku diri doonto</p></div></header><fieldset class="pay-options"><legend class="pay-sr">Choose a payment method / Dooro habka lacag bixinta</legend>${payMethods.map((m,i)=>`<div class="pay-method ${i===0?'is-selected':''}"><label class="pay-choice"><input type="radio" name="payment-method" value="${m.id}" aria-controls="pay-panel-${m.id}" ${i===0?'checked':''}><span class="pay-radio"></span>${brand(m)}<span class="pay-sr">${m.name}</span><span class="pay-chevron">${icon('arrow')}</span></label><div id="pay-panel-${m.id}" class="pay-expand" ${i===0?'':'inert'}><div><section class="pay-panel" aria-label="${m.title} tilmaamaha"><h3>${m.title}</h3><p>${m.id==='sim'?'Send payment to this number / Lacagta ugu soo dir lambarkan':'Dial this code to pay / Ku bixi lacagta adigoo garaacaya'}</p><a class="pay-code" href="tel:${m.tel}" aria-label="Dial ${m.code}">${icon('phone')}<strong>${m.code}</strong></a><a class="pay-dial" href="tel:${m.tel}">${icon('phone')}<span>${m.id==='sim'?'Call / Send payment · Wac / Dir Lacagta':'Open keypad / Fur Keypad-ka'}</span>${icon('arrow')}</a><div class="pay-info">${icon('info')}<span>${m.id==='sim'?'Send the displayed amount to the number above. Check the recipient and amount before confirming. / U dir lacagta kor ku qoran lambarka kore. Hubi magaca qaataha iyo lacagta ka hor intaadan xaqiijin.':'Tap to open your phone keypad, then dial the code. Some devices require manual entry. / Riix si keypad-ku u furmo, kadib garaac koodhka. Taleefannada qaar gacanta ayaa lagu qoraa.'}</span></div><small class="pay-recipient">Recipient / Magaca qaataha: <b>ABDIWAHID</b></small></section></div></div></div>`).join('')}</fieldset><div class="pay-trust"><span class="pay-icon">${icon('shield')}</span><div><strong>Safe &amp; Simple / Ammaan &amp; Fudud</strong><p>Send your payment securely / Lacagtaada si ammaan ah u dir</p></div></div><p class="pay-verification">Opening the keypad does not confirm payment or unlock the book. Contact us for manual verification. / Furitaanka keypad-ku ma xaqiijiyo lacag-bixinta, buuggana si otomaatig ah uma furayo. Kadib markaad dirto, <a href="https://wa.me/252618248533?text=${encodeURIComponent('Salaan, waxaan rabaa xaqiijinta lacagta buugga: '+b.title+' ($'+amount+').')}" target="_blank" rel="noopener">Contact / La xiriir Akram Library</a> si loo hubiyo. If the keypad does not open, enter the code manually. / Haddii keypad-ku furmi waayo, gacanta ku qor lambarka kore.</p></section>`;
const out=document.getElementById('offer-content');
if(!ready){out.querySelector('.pay-options').hidden=true;out.querySelector('.pay-verification').textContent='Payments are not activated for this book. Please do not send money yet. / Lacag-bixinta buuggan weli lama hawlgelin. Fadlan lacag ha dirin.';}
else {await addOrderForm(b,out);}
if(!dialog.open)dialog.showModal();dialog.scrollTop=0;
}catch{document.getElementById('offer-content').textContent='Unable to load payment details. Please refresh. / Dalabka ma furmin; bogga cusboonaysii.';if(!dialog.open)dialog.showModal()}};
async function addOrderForm(b,out){
const user=await window.Akram.user();const node=document.createElement('section');node.className='pay-order';out.append(node);
if(!user){out.querySelector('.pay-options').hidden=true;node.innerHTML='<p>Sign in before paying so your book can be linked to your account. / Soo gal ka hor lacag-bixinta si buugga akoonkaaga loogu xiro.</p><a class="pay-dial" href="account.html?view=signin">Sign in / Soo gal →</a>';return}
const c=await window.Akram.client();const existing=window.Akram.check(await c.from('akram_orders').select('*').eq('book_id',b.id).maybeSingle());
if(existing?.status==='pending'){out.querySelector('.pay-options').hidden=true;node.innerHTML='<p role="status">Payment reference submitted. Awaiting owner verification. Do not pay again. / Tixraaca waa la gudbiyey; sug hubinta maamulka. Mar kale lacag ha bixin.</p><a href="purchases.html">View order / Eeg dalabka →</a>';return}
node.innerHTML=`<h3>Already paid? / Ma bixisay?</h3><p>Enter the transaction ID from your receipt, never your PIN. / Geli lambarka tixraaca rasiidka, ha gelin PIN.</p><form><label>Transaction ID / Tixraaca lacagta<input name="reference" required minlength="4" maxlength="100" autocomplete="off"></label><button type="submit" class="pay-dial">Submit for review / U dir hubin</button><p role="status"></p></form><p><a href="purchases.html">My purchases / Buugaagtayda →</a></p>`;
node.querySelector('form').onsubmit=async e=>{e.preventDefault();const form=e.target,button=form.querySelector('button');button.disabled=true;try{window.Akram.check(await c.rpc('akram_submit_order',{p_book:b.id,p_method:out.querySelector('[name="payment-method"]:checked').value,p_reference:form.elements.reference.value.trim()}));node.innerHTML='<p role="status">Submitted. Please wait for verification; do not pay again. / Waa la gudbiyey. Sug hubinta; mar kale lacag ha bixin.</p><a href="purchases.html">View order / Eeg dalabka →</a>';out.querySelector('.pay-options').hidden=true}catch(err){form.querySelector('[role="status"]').textContent=err.message;button.disabled=false}};
}
async function liveShop(){const grid=document.getElementById('live-shop-grid');if(!grid)return;try{const items=await window.Akram.catalog();grid.innerHTML=items.sort((a,b)=>Number(b.paid)-Number(a.paid)||(['dhis-naftaada','ganacsade','xuska-mawliidka','maxaynu-u-dhibaataysannahay'].indexOf(a.id)+1||999)-(['dhis-naftaada','ganacsade','xuska-mawliidka','maxaynu-u-dhibaataysannahay'].indexOf(b.id)+1||999)).slice(0,4).map(b=>`<article class="shop-product"><div class="shop-cover"><img src="${esc(b.cover)}" alt="${esc(b.title)}" loading="lazy"></div><small>${esc(b.category)} · ${esc(b.language)}</small><h3>${esc(b.title)}</h3><p>${esc(b.author)}</p><div class="shop-price"><strong>${b.paid?'$'+Number(b.price).toFixed(2):'Free / Bilaash'}</strong></div><button class="shop-action" ${b.paid?'data-offer':'data-read'}="${esc(b.id)}">${b.paid?'Open / Fur →':'Read / Akhri →'}</button></article>`).join('')}catch{grid.textContent='Collection unavailable / Buugaagta ma furmin.'}}
liveShop();
dialog.addEventListener('change',e=>{if(e.target.name!=='payment-method')return;dialog.querySelectorAll('.pay-method').forEach(row=>{const active=row.querySelector('input').checked;row.classList.toggle('is-selected',active);row.querySelector('.pay-expand').inert=!active})});
document.addEventListener('click',e=>{const a=e.target.closest('[data-offer]');if(a){e.preventDefault();window.showBookOffer(a.dataset.offer)}});
dialog.querySelector('.shop-close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
const note=document.querySelector('.shop-sales-note');if(note){note.removeAttribute('data-en');note.removeAttribute('data-so');note.textContent='Paid books: select a book to view payment methods. Payment verification and access are handled manually. / Buugaagta lacagta ah: dooro buugga si aad u aragto hababka lacag-bixinta. Xaqiijinta lacagta iyo furitaanka buugga waa gacanta maamulka.'}
const offer=new URL(location.href).searchParams.get('offer');if(offer)window.showBookOffer(offer);
})();
