const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const fs=require('fs'),assert=require('assert');
(async()=>{const http=require('http'),path=require('path');const server=http.createServer((req,res)=>{const file=path.join(process.cwd(),'akram-upload-ready',decodeURIComponent(new URL(req.url,'http://local').pathname).replace(/^\//,'')||'index.html');try{const ext=path.extname(file);res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.webp':'image/webp','.jpg':'image/jpeg','.png':'image/png','.txt':'text/plain'})[ext]||'application/octet-stream');res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end()}});await new Promise(r=>server.listen(8765,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.AKRAM_CHROMIUM||(fs.existsSync('/tmp/akram-browser/chromium')?'/tmp/akram-browser/chromium':undefined),headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'],env:{...process.env,LD_LIBRARY_PATH:'/tmp/akram-browser/al2023/lib:/tmp/akram-browser',FONTCONFIG_PATH:'/tmp/akram-browser/fonts'}});
const books=JSON.parse(fs.readFileSync('akram-upload-ready/catalog.json','utf8'));const errors=[];let passed=0;function ok(v,m){assert(v,m);passed++;}
for(const width of [1440,390]){const ctx=await browser.newContext({viewport:{width,height:1000},deviceScaleFactor:1});const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));
await page.route('**/backend.js*',r=>r.fulfill({contentType:'text/javascript',body:`window.Akram={enabled:true,catalog:async()=>${JSON.stringify(books)},client:async()=>({auth:{onAuthStateChange:(cb)=>{cb('INITIAL_SESSION',null);return {data:{subscription:{unsubscribe(){}}}}},getSession:async()=>({data:{session:null}}),signOut:async()=>({error:null})}}),access:async()=>false,user:async()=>null,check:r=>{if(r.error)throw r.error;return r.data}};`}));
await page.route('**/rest/v1/akram_reviews*',r=>r.fulfill({contentType:'application/json',body:'[]'}));await page.route('**/rest/v1/rpc/akram_subscribe',r=>r.fulfill({contentType:'application/json',body:'null'}));
await page.goto('http://127.0.0.1:8765/',{waitUntil:'networkidle',timeout:30000});await page.locator('#akram-storefront .sf-book-card').first().waitFor();
await page.evaluate(()=>document.getElementById('books').scrollIntoView({behavior:'instant'}));await page.waitForTimeout(500);
await page.evaluate(()=>{document.documentElement.style.scrollSnapType='none';document.documentElement.style.scrollBehavior='auto';window.scrollTo(0,document.getElementById('books').getBoundingClientRect().top+scrollY)});await page.waitForTimeout(150);await page.screenshot({path:`akram-storefront-src/verification/collection-${width}.png`});await page.locator('#akram-storefront').screenshot({path:`akram-storefront-src/verification/library-full-${width}.png`});
ok(await page.locator('#curated .sf-book-card').count()===6,'curated six');ok(await page.locator('#catalogue .sf-book-card').count()===12,'catalogue twelve');ok(await page.locator('#english-collection .sf-book-card').count()===6,'English six');ok(await page.locator('#somali-collection .sf-book-card').count()===6,'Somali six');
ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'no horizontal overflow '+width);
await page.locator('#collection-search').fill('zzzz-unmatched');ok(await page.locator('#catalogue .sf-empty').count()===1,'empty search');await page.locator('#collection-search').fill('Meditations');ok(await page.locator('#catalogue .sf-book-card').count()===1,'search title');await page.locator('#catalogue .sf-catalog-meta button').click();
await page.locator('.sf-search-row>button').click();await page.locator('.sf-filter-controls select').nth(1).selectOption('Somali');ok((await page.locator('#catalogue .sf-book-category').allTextContents()).every(s=>s.includes('Somali')),'language filter');await page.locator('#catalogue .sf-catalog-meta button').click();
await page.locator('#curated .sf-book-card').first().locator('.sf-wishlist').click();ok(await page.locator('#fav-count').textContent()==='1','wishlist count');
await page.locator('#curated .sf-book-card').first().locator('.sf-add').click();await page.locator('.sf-bag').click();await page.locator('.sf-drawer').waitFor();ok(await page.locator('.sf-cart-item').count()===1,'cart add');await page.locator('.sf-cart-item .sf-icon').click();ok(await page.locator('.sf-cart .sf-empty').count()===1,'cart remove');await page.locator('.sf-dialog-top .sf-icon').click();
await page.locator('#english-collection .sf-cover-button').nth(1).click();await page.locator('.sf-detail').waitFor();ok(await page.locator('.sf-detail-copy h2').textContent()==='Meditations','details');await page.locator('.sf-detail').screenshot({path:`akram-storefront-src/verification/details-${width}.png`});await page.locator('.sf-detail-actions .sf-primary').click();await page.locator('.sf-reader-paper p').first().waitFor();const before=await page.locator('.sf-reader-paper').textContent();await page.locator('.sf-reader-bottom button[aria-label=Next]').click();ok(await page.locator('.sf-reader-paper').textContent()!==before,'reader next');await page.locator('.sf-reader-bottom button[aria-label=Previous]').click();ok(await page.locator('.sf-reader-bottom input').inputValue()==='1','reader previous');await page.locator('.sf-reader-bottom input').fill('20');await page.locator('.sf-reader-bottom input').press('Tab');await page.waitForTimeout(350);await page.screenshot({path:`akram-storefront-src/verification/reader-${width}.png`});await page.mouse.move(700,30);await page.locator('.sf-reader-bottom button').filter({hasText:'Aa'}).click();await page.locator('.sf-themes button').nth(1).click();ok(await page.locator('.sf-theme-sepia').count()===1,'sepia theme');await page.locator('.sf-reader-panel textarea').fill('My reading note');await page.locator('.sf-reader-panel button').filter({hasText:'Save note / highlight'}).click();ok(await page.locator('.sf-reader-panel').textContent().then(t=>t.includes('My reading note')),'note saved');await page.locator('.sf-dialog-top .sf-icon').click();
await page.evaluate(()=>window.scrollTo(0,document.querySelector('.welcome-environment').getBoundingClientRect().top+scrollY));await page.locator('.welcome-environment').screenshot({path:`akram-storefront-src/verification/welcome-${width}.png`});
await page.locator('[data-toggle-lang]').first().click();await page.waitForFunction(()=>document.querySelector('.lib-greeting h2')?.textContent.includes('Adduun'));ok(true,'Somali switch');await page.locator('[data-toggle-lang]').first().click();
await page.locator('#newsletter-email').fill('reader@example.com');await page.locator('.sf-subscribe button').click();await page.locator('.sf-subscribe-message').filter({hasText:'Thank you'}).waitFor();ok(true,'newsletter mocked response');
await page.waitForTimeout(4500);await page.evaluate(()=>{window.scrollTo(0,document.getElementById('curated').getBoundingClientRect().top+scrollY-85)});await page.waitForTimeout(150);await page.screenshot({path:`akram-storefront-src/verification/books-${width}.png`});
await ctx.close();}
ok(errors.length===0,errors.join('\n'));console.log('PASS '+passed+' assertions. Local catalog fixture and mocked auth/newsletter; not live payment testing.');await browser.close();server.close();})().catch(e=>{console.error(e);process.exit(1)});
